# Generated by Django 5.0 on 2024-01-23 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buss', '0002_subject_student_assignment_submission_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(limit_choices_to={'teacher': True}, on_delete=django.db.models.deletion.CASCADE, to='buss.user'),
        ),
    ]
